[project]
name = "learn-milvus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pymilvus[model]>=2.5.8",
    "scipy>=1.15.3",
    "torch>=2.7.0",
]
